### ISSUE TITLE
Simulator Code

### ISSUE THREAD

**Issue by Yuan-Zhuo** [arget4me/RigidBody#2]
Hey, I'm new to physical engine. But I have a sub-task to simulate a cube's trajectory when it hits the ground after free fall. So would you please tell me how can I deploy your simulator code in my scenario? I just need every locations. Thank you!

**Comment by arget4me** [comment]
This code handles physics with an impulse based system, as in the book (Millington, I. (2007). Game physics engine development) I recommend it as a good starting point if you're new to physics engines. This was the first physics programming for me and that book helped a lot. 

The impulses generates linear and angular velocities that is applied to the objects. The impulses from collision responses is calculated in [RigidBody.cpp](https://github.com/arget4me/RigidBody/blob/master/src/Physics/RigidBody.cpp). I did some clean up and removed distracting comments and old code. Take a look and see if it helps, it starts from the function **void applyRigidBodyPhysics(Scene3D& scene)**, ask if you get stuck in any part.

**Comment by Yuan-Zhuo** [comment]
Thank u a lot. I have finished two naive simulation works refer to your code.
